# Generated by Django 4.1 on 2023-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0016_rename_logos_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='amenities_images')),
            ],
        ),
        migrations.DeleteModel(
            name='amenities',
        ),
        migrations.DeleteModel(
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='web_image',
        ),
    ]
