# Generated by Django 4.1 on 2023-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0017_amenities_header_delete_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='amenities_images')),
            ],
        ),
        migrations.DeleteModel(
            name='amenities_header',
        ),
    ]
