# Generated by Django 4.1 on 2023-06-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0019_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='number_of_bedrooms',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='sq_ft',
            new_name='title',
        ),
    ]
