# Generated by Django 4.1 on 2023-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0020_rename_number_of_bedrooms_configuration_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('text', models.TextField(max_length=30)),
            ],
        ),
    ]
