# Generated by Django 4.1 on 2023-06-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0023_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
