# Generated by Django 4.1 on 2023-06-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0024_alter_introduction_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
