# Generated by Django 4.1 on 2023-06-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0026_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='third_logo',
            field=models.ImageField(default='', upload_to='logo_images'),
            preserve_default=False,
        ),
    ]
