# Generated by Django 4.1 on 2023-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0035_alter_enquire_now_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire_now',
            name='Last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquire_now',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquire_now',
            name='enquiry_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquire_now',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
