# Generated by Django 4.2.1 on 2023-06-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0036_alter_enquire_now_last_name_alter_enquire_now_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('phase1', models.TextField(max_length=100)),
            ],
        ),
    ]
