# Generated by Django 4.2.1 on 2023-06-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0038_rename_phase1_registration_discription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='webp_image',
        ),
    ]
