# Generated by Django 4.2.1 on 2023-06-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0040_alter_overview_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='configuration1',
        ),
    ]
