# Generated by Django 4.2.5 on 2023-09-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beyondnatureapp', '0041_delete_configuration1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquire_now',
            old_name='Last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='enquire_now',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='introduction',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='text',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
